In [1]:
import pandas as pd
import torch
print("GPU:",torch.cuda.get_device_name(0))

GPU: NVIDIA GeForce RTX 4060 Ti

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [5]:
indep = dataset[['Age', 'EstimatedSalary',  'Gender_Male']]
depend = dataset[['Purchased']]

In [6]:
depend.value_counts()

Purchased
0            257
1            143
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(indep,depend,test_size=0.30,random_state=0)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

svc_param_grid = {
    "C": [0.1, 1, 10, 100],
    "kernel": ["linear", "rbf", "poly"],
    "gamma": ["scale", "auto"],
    "degree": [2, 3, 4]   
}




grid = GridSearchCV(SVC(), svc_param_grid, refit=True ,n_jobs=3, scoring='f1_weighted')
grid.fit(X_train,y_train)

In [ ]:
re = grid.cv_results_
print("The classification value for best parameter {}:".format(grid.best_params_))
table = pd.DataFrame.from_dict(re)
table

In [ ]:
y_pred = grid.predict(X_test)
y_pred

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)

In [ ]:
from sklearn.metrics import classification_report
report= classification_report(y_test, y_pred)
print(report)