In [1]:
import pandas as pd
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
NVIDIA GeForce RTX 4060 Ti

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [6]:
dependent = dataset[["charges"]]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [30]:
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test = train_test_split(independent,dependent, test_size=0.30, random_state=0)

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid = {
    'criterion':['squared_error','friedman_mse',
              'absolute_error','poisson'
             ],
    'max_features':['sqrt','log2',None ]
}
grid = GridSearchCV(RandomForestRegressor(),param_grid, refit=True,verbose=3, n_jobs=1)


grid.fit(independent,dependent)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END criterion=squared_error, max_features=sqrt;, score=0.857 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=squared_error, max_features=sqrt;, score=0.775 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt;, score=0.863 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt;, score=0.832 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=squared_error, max_features=sqrt;, score=0.842 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2;, score=0.858 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2;, score=0.777 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=squared_error, max_features=log2;, score=0.859 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2;, score=0.829 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=squared_error, max_features=log2;, score=0.836 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=None;, score=0.848 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=squared_error, max_features=None;, score=0.775 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=None;, score=0.854 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=squared_error, max_features=None;, score=0.821 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=None;, score=0.837 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=friedman_mse, max_features=sqrt;, score=0.858 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt;, score=0.782 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=friedman_mse, max_features=sqrt;, score=0.866 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt;, score=0.824 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=friedman_mse, max_features=sqrt;, score=0.842 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2;, score=0.857 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2;, score=0.776 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=friedman_mse, max_features=log2;, score=0.862 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2;, score=0.832 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=friedman_mse, max_features=log2;, score=0.842 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=None;, score=0.852 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=friedman_mse, max_features=None;, score=0.781 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=None;, score=0.848 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=friedman_mse, max_features=None;, score=0.820 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=None;, score=0.834 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=absolute_error, max_features=sqrt;, score=0.858 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=absolute_error, max_features=sqrt;, score=0.781 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=absolute_error, max_features=sqrt;, score=0.857 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=absolute_error, max_features=sqrt;, score=0.826 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=absolute_error, max_features=sqrt;, score=0.844 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=absolute_error, max_features=log2;, score=0.853 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=absolute_error, max_features=log2;, score=0.776 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=absolute_error, max_features=log2;, score=0.858 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=absolute_error, max_features=log2;, score=0.827 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=absolute_error, max_features=log2;, score=0.847 total time=   0.4s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=absolute_error, max_features=None;, score=0.836 total time=   0.7s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=absolute_error, max_features=None;, score=0.767 total time=   0.7s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=absolute_error, max_features=None;, score=0.846 total time=   0.7s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=absolute_error, max_features=None;, score=0.824 total time=   0.8s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=absolute_error, max_features=None;, score=0.837 total time=   0.7s
[CV 1/5] END criterion=poisson, max_features=sqrt;, score=0.858 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=poisson, max_features=sqrt;, score=0.781 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=sqrt;, score=0.860 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=poisson, max_features=sqrt;, score=0.828 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=sqrt;, score=0.841 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END criterion=poisson, max_features=log2;, score=0.860 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=log2;, score=0.777 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END criterion=poisson, max_features=log2;, score=0.861 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=log2;, score=0.829 total time=   0.0s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END criterion=poisson, max_features=log2;, score=0.844 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=None;, score=0.848 total time=   0.1s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END criterion=poisson, max_features=None;, score=0.767 total time=   0.1s
[CV 3/5] END criterion=poisson, max_features=None;, score=0.856 total time=   0.1s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END criterion=poisson, max_features=None;, score=0.817 total time=   0.1s
[CV 5/5] END criterion=poisson, max_features=None;, score=0.839 total time=   0.1s

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2', None]},
             verbose=3)

In [10]:
re = grid.cv_results_
print("The R_Score value for best parameter {}:".format(grid.best_params_))

The R_Score value for best parameter {'criterion': 'poisson', 'max_features': 'log2'}:

In [11]:
table = pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.100623,0.001574,0.005400,0.000491,squared_error,sqrt,"{'criterion': 'squared_error', 'max_features':...",0.856742,0.774846,0.863389,0.832263,0.841578,0.833763,0.031433,4
1,0.098907,0.001396,0.004601,0.000492,squared_error,log2,"{'criterion': 'squared_error', 'max_features':...",0.857925,0.777412,0.858693,0.829133,0.835772,0.831787,0.029620,8
2,0.142242,0.000254,0.005000,0.000001,squared_error,None,"{'criterion': 'squared_error', 'max_features':...",0.847696,0.775320,0.854005,0.820683,0.837312,0.827003,0.028195,9
3,0.099018,0.002285,0.005001,0.000634,friedman_mse,sqrt,"{'criterion': 'friedman_mse', 'max_features': ...",0.857810,0.781989,0.865662,0.823701,0.841502,0.834133,0.029789,2
4,0.099617,0.001205,0.005201,0.000402,friedman_mse,log2,"{'criterion': 'friedman_mse', 'max_features': ...",0.857075,0.775641,0.862389,0.832467,0.842222,0.833959,0.031029,3
5,0.141631,0.001056,0.004800,0.000400,friedman_mse,None,"{'criterion': 'friedman_mse', 'max_features': ...",0.852016,0.780925,0.847797,0.819713,0.833925,0.826875,0.025621,10
6,0.457067,0.007410,0.005002,0.000001,absolute_error,sqrt,"{'criterion': 'absolute_error', 'max_features'...",0.857555,0.780566,0.857073,0.825647,0.843972,0.832962,0.028657,6
7,0.459241,0.008074,0.005202,0.000401,absolute_error,log2,"{'criterion': 'absolute_error', 'max_features'...",0.853044,0.776213,0.857947,0.826608,0.847193,0.832201,0.029960,7
8,0.818622,0.015543,0.005102,0.000203,absolute_error,None,"{'criterion': 'absolute_error', 'max_features'...",0.835734,0.766674,0.846262,0.824081,0.837277,0.822006,0.028551,12
9,0.122221,0.003111,0.005003,0.000550,poisson,sqrt,"{'criterion': 'poisson', 'max_features': 'sqrt'}",0.857574,0.780582,0.860197,0.828069,0.840541,0.833393,0.028885,5
10,0.122121,0.001771,0.005201,0.000401,poisson,log2,"{'criterion': 'poisson', 'max_features': 'log2'}",0.860123,0.777347,0.861007,0.828922,0.843674,0.834214,0.030791,1
11,0.171015,0.000837,0.004702,0.000399,poisson,None,"{'criterion': 'poisson', 'max_features': None}",0.848040,0.766789,0.856038,0.817440,0.838915,0.825444,0.032039,11

In [24]:
prediction = grid.predict([[22,34,0,1,1]])
print('prediction={}'.format(prediction))

prediction=[34442.324247]

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(