In [54]:
import pandas as pd
import torch
print("GPU:",torch.cuda.get_device_name(0))

GPU: NVIDIA GeForce RTX 4060 Ti

In [55]:
dataset = pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [56]:
dataset=pd.get_dummies(dataset, dtype=int,drop_first=True)

In [57]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [58]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [59]:
independent = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dependent = dataset[['classification_yes']]

In [60]:
dependent.value_counts()

classification_yes
1                     249
0                     150
Name: count, dtype: int64

In [61]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,1,0,0,0,0,0,0,1,1,0
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,1,0,0,0,0,0,1,0,0
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,1,0,0,0,0,0,1,0,0
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,1,0,0,0,0,0,1,0,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,1,0,0,0,0,0,1,0,0
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,1,0,0,1,1,0,1,0,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,1,0,0,1,1,0,0,0,0
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,1,0,0,1,1,0,1,0,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,1,0,0,0,0,0,1,0,0

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [63]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [64]:
X_train

array([[-0.67992978,  0.26534721,  0.13647691, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.30730707,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.43071168,  1.80469462,  2.56692738, ...,  0.50671171,
        -0.51229234,  2.28035085],
       ...,
       [-0.43312057,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [-1.35865512,  0.26534721, -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [-0.06290675, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901]])

In [65]:
X_test

array([[-0.37141827, -0.5043265 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.8626278 ,  1.03502091,  0.94662707, ..., -1.97350876,
        -0.51229234, -0.43852901],
       [ 1.04773471, -0.5043265 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       ...,
       [-1.35865512, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 0.43071168, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901],
       [ 1.10943702, -1.2740002 , -0.67367325, ...,  0.50671171,
        -0.51229234, -0.43852901]])

In [93]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

param_grid = {
    "C": [0.1, 1, 10, 100, 1000],
    "kernel": ["linear",  "rbf", "poly", "sigmoid"
              ],
    "gamma": ["scale", "auto"],   
}

grid = GridSearchCV(
    SVC(probability=True),
    param_grid,
    scoring="f1_weighted",    
    n_jobs=-3,
     refit=True
)

grid.fit(X_train, y_train)

C:\Users\Admin\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVC(probability=True), n_jobs=-3,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted')

In [94]:
results = pd.DataFrame(grid.cv_results_)
print("The classification value for best parameter {}:".format(grid.best_params_))
results

The classification value for best parameter {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}:

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003600,0.000490,0.005408,1.019675e-03,0.1,scale,linear,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,0.946663,1.000000,1.000000,0.989333,0.021335,5
1,0.009608,0.000490,0.006212,7.490579e-04,0.1,scale,rbf,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}",0.964572,0.982221,0.946663,1.000000,0.981894,0.975070,0.018091,33
2,0.008907,0.000664,0.005414,8.610521e-04,0.1,scale,poly,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'poly'}",0.480769,0.520202,0.480769,0.480769,0.472319,0.486966,0.016937,39
3,0.008912,0.001025,0.005614,8.017536e-04,0.1,scale,sigmoid,"{'C': 0.1, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.982221,0.964572,0.964572,0.982221,0.981894,0.975096,0.008594,31
4,0.003702,0.000400,0.004816,7.554682e-04,0.1,auto,linear,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,0.946663,1.000000,1.000000,0.989333,0.021335,5
5,0.009326,0.000749,0.006208,1.330599e-03,0.1,auto,rbf,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'rbf'}",0.964572,0.982221,0.946663,1.000000,0.981894,0.975070,0.018091,33
6,0.009320,0.001363,0.006010,1.143063e-03,0.1,auto,poly,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'poly'}",0.480769,0.480769,0.480769,0.480769,0.472319,0.479079,0.003380,40
7,0.009713,0.001168,0.005706,1.169232e-03,0.1,auto,sigmoid,"{'C': 0.1, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.982221,0.964572,0.964572,0.982221,0.981894,0.975096,0.008594,31
8,0.007112,0.000664,0.004903,8.004666e-04,1.0,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,1.000000,0.982221,0.982221,1.000000,0.989333,0.008710,7
9,0.006806,0.000750,0.005012,1.168008e-07,1.0,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.964286,1.000000,0.981894,0.985680,0.013373,21
10,0.006408,0.000197,0.006105,1.596016e-03,1.0,scale,poly,"{'C': 1, 'gamma': 'scale', 'kernel': 'poly'}",0.982051,0.982051,0.964286,0.963889,0.981728,0.974801,0.008749,37
11,0.004504,0.000316,0.006506,1.704608e-03,1.0,scale,sigmoid,"{'C': 1, 'gamma': 'scale', 'kernel': 'sigmoid'}",1.000000,1.000000,0.946663,1.000000,0.981894,0.985711,0.020745,15
12,0.006005,0.001706,0.006005,1.141495e-03,1.0,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,1.000000,0.982221,0.982221,1.000000,0.989333,0.008710,7
13,0.010411,0.002786,0.006006,5.492138e-04,1.0,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.964286,1.000000,0.981894,0.985680,0.013373,21
14,0.012115,0.003176,0.006509,1.050792e-03,1.0,auto,poly,"{'C': 1, 'gamma': 'auto', 'kernel': 'poly'}",0.982051,0.982051,0.964286,0.963889,0.981728,0.974801,0.008749,37
15,0.011919,0.003554,0.005104,1.022516e-03,1.0,auto,sigmoid,"{'C': 1, 'gamma': 'auto', 'kernel': 'sigmoid'}",1.000000,1.000000,0.946663,1.000000,0.981894,0.985711,0.020745,15
16,0.008708,0.003144,0.005914,3.717220e-04,10.0,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
17,0.012920,0.003523,0.005306,1.209370e-03,10.0,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,1.000000,1.000000,0.992854,0.008752,3
18,0.014321,0.003694,0.004909,8.015040e-04,10.0,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",1.000000,1.000000,0.964286,1.000000,0.981894,0.989236,0.014311,13
19,0.013722,0.002237,0.004909,9.691618e-04,10.0,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.982221,1.000000,0.982221,1.000000,1.000000,0.992888,0.008710,1
20,0.011816,0.001841,0.005710,5.089385e-04,10.0,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
21,0.014128,0.002166,0.005302,6.784802e-04,10.0,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,1.000000,1.000000,0.992854,0.008752,3
22,0.016827,0.001406,0.005709,6.761054e-04,10.0,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",1.000000,1.000000,0.964286,1.000000,0.981894,0.989236,0.014311,13
23,0.015525,0.001143,0.005609,7.371083e-04,10.0,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.982221,1.000000,0.982221,1.000000,1.000000,0.992888,0.008710,1
24,0.015729,0.000512,0.005104,6.662852e-04,100.0,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
25,0.015630,0.000799,0.005401,7.998244e-04,100.0,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,9
26,0.024033,0.008720,0.005508,7.078074e-04,100.0,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.964572,1.000000,0.982051,1.000000,0.981894,0.985703,0.013290,19
27,0.017119,0.004083,0.005609,1.020586e-03,100.0,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.982221,0.982051,0.982221,0.982051,1.000000,0.985709,0.007146,17
28,0.016526,0.004510,0.005502,6.308286e-04,100.0,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
29,0.016824,0.003898,0.005102,4.911008e-04,100.0,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,9
30,0.016921,0.000971,0.005403,4.897654e-04,100.0,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.964572,1.000000,0.982051,1.000000,0.981894,0.985703,0.013290,19
31,0.010712,0.005484,0.004305,4.021863e-04,100.0,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.982221,0.982051,0.982221,0.982051,1.000000,0.985709,0.007146,17
32,0.012419,0.005219,0.005202,4.001767e-04,1000.0,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
33,0.012617,0.004333,0.005100,4.896878e-04,1000.0,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,9
34,0.017630,0.010305,0.005204,5.097609e-04,1000.0,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,23
35,0.015823,0.009096,0.004612,4.880041e-04,1000.0,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.982221,0.946663,0.982221,0.982051,0.981894,0.975010,0.014174,35
36,0.008309,0.005918,0.004802,6.782353e-04,1000.0,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.982221,0.982221,0.982221,0.982051,0.981894,0.982122,0.000132,25
37,0.007805,0.004267,0.005118,9.796861e-04,1000.0,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.982221,1.000000,0.982051,0.982051,1.000000,0.989265,0.008766,9
38,0.015942,0.000490,0.004802,7.492459e-04,1000.0,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.964572,1.000000,0.964286,1.000000,0.981894,0.982150,0.015909,23
39,0.013936,0.001243,0.004703,3.988335e-04,1000.0,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.982221,0.946663,0.982221,0.982051,0.981894,0.975010,0.014174,35

In [95]:
y_pred = grid.predict(X_test)
y_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [96]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[45  2]
 [ 0 73]]

In [97]:
from sklearn.metrics import classification_report
report= classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        45
           1       1.00      0.97      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.99      0.98       120
weighted avg       0.98      0.98      0.98       120

In [99]:
y_prob = grid.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, y_prob)

print(auc)

0.9997037037037036